Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0080e4c5bc078760e # Amazon Linux AMI in N. Virginia
    us-east-2:
      AMI: ami-0cd3dfa4e37921605 # Amazon Linux AMI in Ohio
    us-west-1:
      AMI: ami-0ec6517f6edbf8044 # Amazon Linux AMI in N. California
    eu-north-1:
      AMI: ami-86fe70f8 # Amazon Linux AMI in Sweden
    ap-southeast-1:
      AMI: ami-05b3bcf7f311194b3 # Amazon Linux AMI in Singapore
    ap-southeast-2:
      AMI: ami-02fd0b06f06d93dfc # Amazon Linux AMI in Sydney
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join
          - " "
          - - "EC2 Instance for "
            - !Ref AWS::Region
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

