Parameters:
  NameOfService:
    Description: "The name of the service this stack is to be used for"
    Type: String # Type always required attribute of Parameters. Can accept: String, Number, List<Number>, CommaDelimitedList, AWS-specific Types (AWS::EC2::Image::ID), Systems Manager Parameter types
  KeyName:
    Description: "Name of an existing EC2 KeyPair to enable SSH access to into the server"
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0080e4c5bc078760e # Amazon Linux AMI in N. Virginia
    us-east-2:
      AMI: ami-0cd3dfa4e37921605 # Amazon Linux AMI in Ohio
    us-west-1:
      AMI: ami-0ec6517f6edbf8044 # Amazon Linux AMI in N. California
    eu-north-1:
      AMI: ami-86fe70f8 # Amazon Linux AMI in Sweden
    ap-southeast-1:
      AMI: ami-05b3bcf7f311194b3 # Amazon Linux AMI in Singapore
    ap-southeast-2:
      AMI: ami-02fd0b06f06d93dfc # Amazon Linux AMI in Sydney
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0


Outputs:
  ServerIp:
    Description:
      The Server IP Address
    Value: !GetAtt
      - Ec2Instance
      - PublicIp


